### ISSUE TITLE
undo implementation in game

### ISSUE THREAD

**Issue by skbelalmd** [skbelalmd/okb-web#24]
Undo during card play not implemented.

**Comment by skbelalmd** [comment]
Implemented undo functionality. But I checked in Okplus. Undo is not working or I mayn't have proper idea how to undo a move.

Farooq sir, Can you check that if Undo is working properly in okplus.

**Comment by farooq-ahmed** [comment]
Yes it's working , in okplus who ever has played last card request for undo then who ever has played second last does undo so last card played is reverted and it can continue till the opening card

**Comment by skbelalmd** [comment]
done.
