### ISSUE TITLE
claiming

### ISSUE THREAD

**Issue by skbelalmd** [skbelalmd/okb-web#26]
Option to claim is shown only for that pair who has won the bid, where as it should come appear on other players as well once they are in a state to claim( will have to check the actual logic when claim button appears in okplus)

**Comment by skbelalmd** [comment]
I have checked in okPlus. 

Claim button only appear during game play and for the player who has won the bid. The same is updated in ok-web.

**Comment by skbelalmd** [comment]
Farooq sir, Have a look at this and correct me if I am wrong.

**Comment by farooq-ahmed** [comment]
after few hands are played you can observe that claim button appears even for pairs who have not win the contract , lets discuss this tomorrow
