### ISSUE TITLE
header alignment

### ISSUE THREAD

**Issue by skbelalmd** [skbelalmd/okb-web#8]
On clicking chat window alignment of list and grid view buttons gets disturbed..

**Comment by skbelalmd** [comment]
![image](https://user-images.githubusercontent.com/15244653/33253265-a33d910e-d368-11e7-89d2-e3891a63e040.png)

**Comment by sagarveer** [comment]
at the same time alignment of table get changed in tablet

**Comment by skbelalmd** [comment]
Fixed it
